# Generated by Django 5.1 on 2025-02-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_bookmarks_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_requested',
            field=models.BooleanField(default=False),
        ),
    ]
