# Generated by Django 5.1 on 2025-02-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_verification_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
