# Generated by Django 5.1 on 2025-02-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='library',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
