# Generated by Django 5.1 on 2025-02-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='followers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
