# Generated by Django 5.1 on 2025-02-10 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_views'),
        ('tag', '0002_tag_followers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_story',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('cover', models.ImageField(upload_to='story_covers/')),
                ('summary', models.TextField()),
                ('reads', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='stories', to='tag.tag')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='blog.story'),
        ),
    ]
