# Generated by Django 5.0.6 on 2025-02-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_is_story_story_blog_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='cover',
            field=models.URLField(max_length=250),
        ),
    ]
